apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-qudm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-qudm
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-qudm
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-qudm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-qudm
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-azzt-tenant/rhtap-demo-app/hacbs-test-project-qudm@sha256:4aefb60c3a5befe529200692eaffd9768dc8f245d0fe6203951d36466fa43fad
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
